#!/usr/bin/env python3
from pathlib import Path
import json, html
ROOT=Path(__file__).resolve().parents[4];P=ROOT/'assets/production/picnic-v1';G=P/'review/world-branding'
body=[]
for aid,title in [('ENV-01','Picnic working world'),('ENV-02','Garden world')]:
    body.append(f'<section id="{aid}"><h2>{aid} · {title}</h2><p>Three independently generated raster sources. The quiet center reserves future working pieces, Pip, reference and controls; they are excluded from this art.</p><div class="scene-grid">')
    for orient in ['landscape','portrait']:
        folder=f'../../masters/images/{aid}/take-02/{orient}/';key=aid+'-'+orient
        body.append(f'<article><h3>{orient.title()}</h3><p class="caption">'+('2732 × 2048' if orient=='landscape' else '2048 × 2732')+' · proposed canvas</p>')
        body.append(f'<div class="scene" data-scene="{key}">')
        for i,role in enumerate(['distant','ground','foreground']):
            body.append(f'<img class="layer layer-{role}" src="{folder}{role}.png" alt="{aid} {orient} registered {role} layer"'+('' if i==0 else ' aria-hidden="true"')+'>')
        body.append('</div><fieldset><legend>Inspect contributions</legend>')
        for role in ['distant','ground','foreground']:
            body.append(f'<label><input type="checkbox" checked data-target="{key}" data-role="{role}">{role.title()}</label>')
        body.append(f'</fieldset><p class="links"><a href="{folder}composite.png">Exact composite PNG</a> · <a href="{folder}editable.ora">Editable OpenRaster</a> · <a href="{key}-exploded.png">Exploded sheet</a></p>')
        body.append('<details><summary>Proposed clearances and catalog slot mapping</summary><p>Outlines below are diagnostics. Overlap in the union combines alternate activity layouts; it does not place all pieces simultaneously. Rectangles are phase proposals, not canonical catalog screen coordinates. Foreground alpha is zero inside every rectangle plus 1.5% margin.</p>')
        for family,label in [('union','Union of all reserved areas'),('LAYOUT-COUNT','Count'),('LAYOUT-JOIN','Join'),('LAYOUT-TAKE','Take away'),('garden','Garden toy / Finish')]:
            legend=json.loads((G/f'{key}-{family}-legend.json').read_text()); items=''.join(f'<li><b>{idx}</b> · {html.escape(item["name"])}</li>' for idx,item in legend.items())
            body.append(f'<details><summary>{label}</summary><img class="diagnostic" src="{key}-{family}-clearance.jpg" alt="{aid} {orient} {label} separate clearance annotations"><ol class="legend">{items}</ol></details>')
        body.append('</details></article>')
    body.append('</div></section>')
body.append('<section id="branding"><h2>Provisional branding</h2><p>Pip’s Picnic remains a working name. Icon, naming, font/composition and rights decisions await human review.</p><div id="brand-results">')
b1=P/'masters/images/BRAND-01/take-01';b2=P/'masters/images/BRAND-02/take-01'
if (b1/'wordmark-editable.svg').exists():
    body.append('<h3>Editable provisional wordmark</h3><img class="brand-sheet" src="../../masters/images/BRAND-01/take-01/wordmark-editable.svg" alt="Pip’s Picnic provisional wordmark using embedded Rubik Bold"><p class="small">Rubik Bold · Version 1.100 · licensed font bundled with recipe. The SVG contains editable text; the native recipe and source font are authoritative.</p>')
if (b1/'branding-sheet.png').exists():
    body.append('<img class="brand-sheet" src="../../masters/images/BRAND-01/take-01/branding-sheet.png" alt="Provisional wordmark and icon branding review sheet">')
if (b2/'icon-small-size-sheet.png').exists():
    body.append('<h3>Unmasked icon · small-size inspection</h3><p>The 1024 square export is opaque. Rabbit silhouette and scarf persist at small sizes; facial detail becomes limited at 16 pixels. Physical home-screen visibility and platform masking remain pending.</p><img class="brand-sheet" src="../../masters/images/BRAND-02/take-01/icon-small-size-sheet.png" alt="Icon at native 16, 32, 64 and 128 pixels, with magnified inspection row"><p><a href="../../masters/images/BRAND-02/take-01/icon-1024.png">Exact opaque 1024 icon</a> · <a href="../../masters/images/BRAND-02/take-01/recovered-icon-original.png">Preserved generated original</a></p>')
body.append('<p><a href="../../masters/images/BRAND-01/take-01/">Wordmark source, font license and reproducible recipe</a> · <a href="../../../../../docs/orchestration/phases/2a-world/branding-evidence.md">Branding inspection and provenance</a></p></div></section>')
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Phase 2A · World and branding review</title><style>
:root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#faf6ed;color:#273d34;font:17px/1.6 ui-rounded,system-ui,sans-serif}main{max-width:1380px;margin:auto;padding:48px 28px 90px}header{max-width:880px;margin-bottom:42px}h1{font-size:clamp(32px,4vw,54px);line-height:1.15;letter-spacing:-.025em;margin:10px 0 22px}h2{font-size:30px;margin:0 0 10px}h3{font-size:23px;margin:0}p{margin:10px 0 22px}.eyebrow{color:#58684e;font-size:15px}.notice{background:#eee9da;padding:18px 22px;border-radius:12px}.caption{font-size:15px;color:#526653;margin:4px 0 12px}.scene-grid{display:grid;grid-template-columns:1fr 1fr;gap:26px;align-items:start}section{margin:0 0 56px;padding-top:16px}article{min-width:0;background:#fffdf6;padding:22px;border-radius:16px;border:1px solid #dedccc}.scene{position:relative;background:repeating-conic-gradient(#dedfd8 0 25%,#f1ece1 0 50%) 0/24px 24px;line-height:0}.layer{width:100%;height:auto;display:block}.layer:not(:first-child){position:absolute;inset:0}.layer.hidden{visibility:hidden}fieldset{margin-top:18px;border:0;padding:0}legend{font-weight:650;margin-bottom:8px}label{display:inline-flex;align-items:center;gap:7px;cursor:pointer;margin-right:16px;padding:4px 0}input{accent-color:#456750;width:18px;height:18px}.links{font-size:15px;margin:14px 0}a{color:#284e66;text-decoration-thickness:1px;text-underline-offset:3px}a:hover{color:#173c4d}a:focus-visible,summary:focus-visible,input:focus-visible{outline:3px solid #c87938;outline-offset:5px}details{padding:12px 0;border-top:1px solid #dedccc}summary{cursor:pointer;font-weight:600;min-height:36px}.diagnostic{display:block;width:100%;height:auto;margin:10px 0}.legend{font-size:14px;list-style:none;padding:0;margin:10px 0;columns:2}.legend li{break-inside:avoid}.small{font-size:15px}.brand-sheet{width:100%;height:auto}.brand-icon{width:240px;max-width:100%}footer{border-top:1px solid #dedccc;padding-top:22px;font-size:15px}nav{display:flex;flex-wrap:wrap;gap:18px;margin:24px 0}@media(max-width:740px){main{padding:28px 16px 56px}.scene-grid{grid-template-columns:1fr}article{padding:16px}.legend{columns:1}h2{font-size:26px}}
</style></head><body><main><header><p class="eyebrow">ADULT REVIEW · PHASE 2A · CANDIDATES</p><h1>A quiet world for the picnic</h1><p>Twelve registered layer exports, four editable masters and provisional branding. Toggle a layer to see its independent contribution.</p><p class="notice"><b>Human acceptance pending.</b> World/art, composition, icon, final name, content, provider rights and family iPad target remain open. This packet checks assets; it does not approve or build the app.</p><nav><a href="#ENV-01">Picnic</a><a href="#ENV-02">Garden</a><a href="#branding">Branding</a><a href="../../metadata/world-audit.json">Decoded audit</a></nav></header>'''+''.join(body)+'''<footer><p>Sources are six separate generated raster artworks. The exported dimensions use disclosed resampling and registration. OpenRaster lets each registered raster layer be painted, masked or replaced independently; it is not vector or editable-object artwork.</p><p>Catalog slots stay region-relative and reproject by identity. No 80–88 pt touch, larger-text, actual object-fit or physical-device usability claim follows from these canvases. Final selected delivery remains a separate decision.</p><p><a href="../../metadata/world-registration.json">Registration and source hashes</a> · <a href="../../metadata/world-safe-regions.json">Coordinate and clearance proposal</a> · <a href="../../../../../docs/orchestration/phases/2a-world/handoff.md">Durable phase handoff</a></p></footer></main><script>document.querySelectorAll('input[data-target]').forEach(input=>input.addEventListener('change',()=>document.querySelector('[data-scene="'+input.dataset.target+'"] .layer-'+input.dataset.role).classList.toggle('hidden',!input.checked)));</script></body></html>'''
(G/'index.html').write_text(page)
print('Created local adult review gallery with all four orientation sources and 20 diagnostic views.')
