'use strict';

const app = document.getElementById('app');
const state = { scene: 'home', picked: new Set(), countDone: false, joined: false, addDone: false, given: false, subtractDone: false, earned: false, placed: false, finished: false, narration: false, music: false, reducedMotion: window.matchMedia('(prefers-reduced-motion: reduce)').matches, level: 'Growing', feedback: '', feedbackType: '' };
const icons = {
  arrow: '<path d="M5 12h14M13 6l6 6-6 6"/>',
  home: '<path d="m3 10 9-7 9 7v10H4V10m5 10v-7h6v7"/>',
  sound: '<path d="M11 4 6 8H3v8h3l5 4V4zm4 4c2 2 2 6 0 8m3-11c4 4 4 10 0 14"/>',
  lock: '<rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 5v2"/>',
  check: '<path d="m5 12 4 4L19 6"/>',
  back: '<path d="M19 12H5m6-6-6 6 6 6"/>',
  leaf: '<path d="M5 20c0-9 2-15 15-16 0 10-3 15-12 14m-3 2L16 9"/>',
};
const icon = (name) => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name] || icons.arrow}</svg>`;

function berry(extra = '', accessible = false) { return `<svg viewBox="0 0 90 110" class="berry-art ${extra}" ${accessible ? 'role="img" aria-label="Berry"' : 'aria-hidden="true"'}><path d="M15 34C0 52 22 97 43 105c19-3 48-46 39-68C73 15 29 15 15 34Z" fill="#D95D47"/><path d="M19 42C15 61 27 81 39 91" fill="none" stroke="#e98164" stroke-width="6" stroke-linecap="round"/><path d="m44 31-24 5 9-13-11-8 21 4 8-16 7 17 23-8-10 16 15 9-28-4-11 9Z" fill="#547f45"/><path d="M47 20 50 6" stroke="#315d3c" stroke-width="5" stroke-linecap="round"/><g fill="#ffe5ad"><ellipse cx="28" cy="48" rx="2.2" ry="3.7" transform="rotate(-14 28 48)"/><ellipse cx="49" cy="50" rx="2.2" ry="3.7"/><ellipse cx="66" cy="48" rx="2.2" ry="3.7" transform="rotate(17 66 48)"/><ellipse cx="34" cy="65" rx="2.2" ry="3.7"/><ellipse cx="58" cy="65" rx="2.2" ry="3.7"/><ellipse cx="46" cy="81" rx="2.2" ry="3.7"/></g></svg>`; }

function pip(extra = '') { return `<svg viewBox="0 0 240 310" class="pip-art ${extra}" aria-hidden="true"><ellipse cx="122" cy="291" rx="79" ry="13" fill="#486740" opacity=".12"/><ellipse cx="64" cy="105" rx="27" ry="77" transform="rotate(-16 64 105)" fill="#efe5ce"/><ellipse cx="161" cy="89" rx="26" ry="80" transform="rotate(13 161 89)" fill="#f7eedc"/><ellipse cx="66" cy="90" rx="11" ry="48" transform="rotate(-16 66 90)" fill="#e8b8a5"/><ellipse cx="162" cy="73" rx="10" ry="47" transform="rotate(13 162 73)" fill="#ecc4af"/><ellipse cx="117" cy="243" rx="66" ry="60" fill="#f6ecd7"/><ellipse cx="184" cy="249" rx="20" ry="20" fill="#e9dec5"/><path d="M61 216c23-20 84-24 111-1l-5 49H66Z" fill="#809873"/><path d="M68 216h96v17H69Z" fill="#748b66"/><path d="M78 209v-19m67 17v-17" stroke="#809873" stroke-width="12"/><circle cx="83" cy="224" r="4" fill="#eddbaf"/><circle cx="146" cy="224" r="4" fill="#eddbaf"/><ellipse cx="116" cy="154" rx="82" ry="72" fill="#f7eedc"/><path d="M51 151c0-24 15-42 31-48" fill="none" stroke="#fff8e9" stroke-width="13" stroke-linecap="round"/><ellipse cx="74" cy="173" rx="14" ry="8" fill="#eac1ae"/><ellipse cx="157" cy="172" rx="14" ry="8" fill="#eac1ae"/><ellipse cx="87" cy="153" rx="4.6" ry="6" fill="#354f3c"/><ellipse cx="145" cy="151" rx="4.6" ry="6" fill="#354f3c"/><path d="M109 169q8-6 15 0l-7 7Z" fill="#b98472"/><path d="M117 176q-1 11-11 6m11-6q1 11 11 5" fill="none" stroke="#6f7257" stroke-width="2.7" stroke-linecap="round"/><ellipse cx="65" cy="239" rx="14" ry="26" transform="rotate(30 65 239)" fill="#f7eedc"/><ellipse cx="165" cy="232" rx="14" ry="26" transform="rotate(-35 165 232)" fill="#f7eedc"/><ellipse cx="84" cy="281" rx="27" ry="15" fill="#eee3cc"/><ellipse cx="150" cy="279" rx="27" ry="15" fill="#f7eedc"/><path d="m120 232-2 21h15" fill="none" stroke="#526d48" stroke-width="2" opacity=".5"/></svg>`; }

function pinwheel(extra = '') { return `<svg viewBox="0 0 120 210" class="pinwheel-art ${extra}" aria-hidden="true"><path d="M60 62v139" stroke="#a88457" stroke-width="7" stroke-linecap="round"/><g class="pinwheel-rotor"><path d="M60 58 9 9h51Z" fill="#eeb64d"/><path d="M60 58V9l49 49Z" fill="#d95d47"/><path d="M60 58h49l-49 49Z" fill="#76a6b0"/><path d="M60 58v49L9 58Z" fill="#819e69"/><path d="M60 58 9 9v49Z" fill="#f4cd65"/><path d="M60 58 109 9H60Z" fill="#ed9775"/><path d="M60 58 109 107V58Z" fill="#b9dadd"/><path d="M60 58 9 107h51Z" fill="#b9c993"/><circle cx="60" cy="58" r="9" fill="#fff7dc"/><circle cx="60" cy="58" r="3" fill="#a5804d"/></g></svg>`; }

function blossom(x, y, scale = 1, color = '#f8cf66') { return `<g transform="translate(${x} ${y}) scale(${scale})"><path d="M0 0v28m0-13q-16-12-16 0 6 9 16 6m0-2q14-16 17-4-4 10-17 10" fill="#719052" stroke="#719052" stroke-width="2"/><g fill="${color}"><ellipse cy="-10" rx="7" ry="11"/><ellipse cx="10" cy="-2" rx="7" ry="11" transform="rotate(60 10 -2)"/><ellipse cx="6" cy="10" rx="7" ry="11" transform="rotate(145 6 10)"/><ellipse cx="-8" cy="9" rx="7" ry="11" transform="rotate(220 -8 9)"/><ellipse cx="-10" cy="-4" rx="7" ry="11" transform="rotate(295 -10 -4)"/></g><circle r="6" fill="#aa7b38"/></g>`; }

function house(x, y, scale = 1) { return `<g transform="translate(${x} ${y}) scale(${scale})"><path d="M0 46h112v100H0Z" fill="#eec880"/><path d="M-15 50 55-9l74 59Z" fill="#cb7157"/><path d="M57 8 115 51" stroke="#e1946e" stroke-width="5" stroke-linecap="round"/><path d="M42 146V99a20 20 0 0 1 40 0v47Z" fill="#708a64"/><circle cx="72" cy="119" r="3" fill="#edd29a"/><path d="M14 67h25v28H14Zm69 0h19v28H83Z" fill="#fff4d6"/><path d="M26 68v26m-11-13h23m55-13v25" stroke="#b49a67" stroke-width="3"/><path d="M89 4v-25h13v34Z" fill="#ba7759"/><path d="M-9 148h134" stroke="#789263" stroke-width="9" stroke-linecap="round"/></g>`; }

function tree(x, y, scale = 1) { return `<g transform="translate(${x} ${y}) scale(${scale})"><path d="M-5 60v97m0-53-27-23m27 3 31-25" fill="none" stroke="#ae8f64" stroke-width="12" stroke-linecap="round"/><path d="M-71 37C-84 11-58-5-42-7c-9-27 32-39 44-23 19-30 65-5 55 21 39 6 34 46 11 53 21 26-17 48-40 34-26 29-66 11-61-6-32 8-55-16-38-35Z" fill="#8fa778"/><path d="M-48 22c5-20 18-16 28-27" stroke="#aac093" fill="none" stroke-width="9" stroke-linecap="round"/><g fill="#d97153"><circle cx="-38" cy="37" r="10"/><circle cx="25" cy="2" r="10"/><circle cx="36" cy="49" r="10"/></g><path d="m-39 25 4-6m59-28 3-7m7 53 4-7" stroke="#547347" stroke-width="3" stroke-linecap="round"/></g>`; }

function homeArt() { return `<svg viewBox="0 0 600 590" role="img" aria-label="Pip the bunny in a sunny garden with a little house, apple tree, flowers and a basket of strawberries"><defs><clipPath id="garden-arch"><path d="M54 508V258C54 115 152 40 302 40s242 84 242 218v250Z"/></clipPath></defs><g clip-path="url(#garden-arch)"><path d="M40 40h520v500H40Z" fill="#dbe9df"/><circle cx="397" cy="141" r="53" fill="#f3ce6b"/><path d="M327 140c-35-8-39 14-66 9-20-3-29-2-34 8h124c2-9-10-13-24-17m-188 40c-23-14-44-4-46 8-27-6-32 8-32 14h121c0-13-28-21-43-22" fill="#fff9ec" opacity=".8"/><path d="M40 342c112-67 181-28 266 1 71-39 183-73 260-25v245H40Z" fill="#c4d3aa"/><path d="M14 430c96-47 166-39 280-4 97-54 189-62 290-30v177H14Z" fill="#a8be8a"/><path d="M259 423q-65 25-64 141h239q-66-109-139-122Z" fill="#ebd6ab"/><path d="M279 448q47 33 75 70" fill="none" stroke="#f5e3bd" stroke-width="16" stroke-linecap="round"/>${house(336,277,.92)}${tree(132,247,1.09)}<path d="M54 454q150-41 286 54l-287 21Z" fill="#92ad74"/>${blossom(481,461,1.0,'#f7ce62')}${blossom(457,473,.65,'#ffedd0')}${blossom(99,457,.62,'#f7eed4')}${blossom(134,473,.9,'#dfa282')}<g fill="#6d8e56"><path d="m373 490 4-20 7 18 7-10 1 19m-187-95-3-13-8 10 2-15-8 11m332 20 5-12 6 16 5-9 2 14"/></g></g><path d="M53 509q139 24 262 12 127-11 230-13" stroke="#a3b886" stroke-width="4" fill="none"/>${pip().replace('<svg ', '<svg x="153" y="227" width="234" height="310" ')}<g transform="translate(305 454) rotate(7)"><path d="M-2 0h96l-10 57H9Z" fill="#c29154"/><path d="M8-2c-5-69 73-71 77 0" fill="none" stroke="#b68048" stroke-width="8"/>${berry().replace('<svg ', '<svg x="18" y="-25" width="35" height="44" ')}${berry().replace('<svg ', '<svg x="45" y="-20" width="35" height="44" ')}<path d="M-5 4h105v12H-5Z" fill="#d2a76d"/><path d="M7 28h82M11 43h75M25 18l4 37m21-37v40m22-40-4 37" stroke="#e0b983" stroke-width="4"/></g>${blossom(461,529,.72,'#d88367')}<g transform="translate(488 245) rotate(-14)"><path d="M0 0c-37-21-41 17-8 14-11 18 11 28 14 4 34 8 31-26 7-15Z" fill="#e8ba61"/><path d="m4 5-2 17" stroke="#826b3f" stroke-width="3"/></g></svg>`; }

function gardenArt() { return `<svg viewBox="0 0 1194 620" preserveAspectRatio="xMidYMax slice" role="img" aria-label="Pip's garden, with a tree, flower beds, a small yellow house and a winding path"><path d="M0 238q162-102 337-49 213 75 386-32 202-84 471 69v394H0Z" fill="#e1e9cf"/><path d="M0 330q195-82 343-7 170 40 322-24 273-91 529 11v310H0Z" fill="#c4d4a6"/><path d="M0 468q242-83 425-15 252-85 461 1 169-30 308 5v161H0Z" fill="#a9bf88"/><path d="M714 393q-143 99-159 227h286q-111-122-74-223Z" fill="#e9d4aa"/><path d="M737 450q-63 78-22 158" fill="none" stroke="#f4dfb6" stroke-width="25" stroke-linecap="round"/>${tree(187,245,1.65)}${house(764,245,1.12)}<path d="M970 330v81m32-81v81m32-81v81m-74-59h85m-85 36h85" stroke="#f8eed3" stroke-width="11" stroke-linecap="round"/>${pip().replace('<svg ', '<svg x="319" y="300" width="178" height="244" ')}<ellipse cx="218" cy="540" rx="119" ry="30" fill="#9dad77"/><path d="M94 548q112-18 229 0" stroke="#8ca466" stroke-width="4" fill="none"/>${blossom(122,503,1.0,'#e9a08a')}${blossom(173,485,1.23,'#fff3d4')}${blossom(221,507,.95,'#eec969')}${blossom(264,483,1.14,'#d98467')}${blossom(308,515,.76,'#fff3d4')}${blossom(941,503,.78)}${blossom(969,484,1.2,'#ffedd0')}${blossom(1031,510,.8,'#df9a7b')}${blossom(1091,441,.66,'#f1ce78')}<g fill="#739153"><path d="m66 422 7-17 4 17 9-13 1 21m446-12 8-19 4 18 7-7 2 16m505-5 8-16 7 18 8-9 1 17m-888 113 7-18 5 17 7-9 2 18"/></g><g fill="#e5edcf"><ellipse cx="545" cy="553" rx="5" ry="2"/><ellipse cx="571" cy="559" rx="4" ry="2"/><ellipse cx="896" cy="430" rx="4" ry="2"/><ellipse cx="911" cy="422" rx="4" ry="2"/></g></svg>`; }

function basket() { return `<svg viewBox="0 0 280 230" aria-hidden="true"><ellipse cx="141" cy="212" rx="99" ry="12" fill="#d5d5b9" opacity=".7"/><path d="M63 88C40-11 240-11 216 90" fill="none" stroke="#bd8d51" stroke-width="11"/><path d="M37 86h207l-21 115q-81 17-165 0Z" fill="#cba266"/><path d="m57 110 7 90m26-92 5 97m32-97 2 100m32-100-1 100m32-100-6 99m34-96-11 88M46 128h186M49 156h182M55 183h172" stroke="#dfbc83" stroke-width="6"/><path d="M28 83h224v24H28Z" fill="#ddb57a"/><path d="M38 90h201" stroke="#e9ca96" stroke-width="4" stroke-linecap="round"/><path d="m37 106 21 95q80 18 165 0l20-95" fill="none" stroke="#ae7f48" stroke-width="3"/></svg>`; }

const notes = {
 home: ['01 / HOME', 'A friend, a place, one clear invitation.', 'Pip welcomes your child into a small, familiar world. Play starts three short activities; the garden is always open. Big art and two choices keep the first screen calm.', 'Try “Play with Pip”'],
 count: ['02 / COUNT', 'Touch the quantity. See where it goes.', 'Six berries make the target meaningful. Tap to pack, tap again to undo, then choose Done. A gentle prompt supports under- and over-counting without a buzzer or lost reward.', 'Pack 5, then tap Done'],
 add: ['03 / ADD', 'The objects tell the story before the symbols.', 'Two berries and one berry move together. Your child chooses how many there are; the equation appears after success. This fixed review scenario is not an adaptive lesson engine.', 'Bring the berries together'],
 subtract: ['04 / TAKE AWAY', 'Taking away has a visible meaning.', 'Five berries become three when Pip receives two. The original positions remain faintly visible, connecting the starting amount, change and result.', 'Give Pip 2 berries'],
 garden: ['05 / GARDEN', 'A little creation, then a natural stopping point.', 'Completing the three activities gives one pinwheel. Place it, spin it, and finish for today. Previewing this scene includes a clearly labeled sample reward. Garden access never depends on performance.', 'Place it, then tap to spin'],
 parents: ['06 / GROWN-UPS', 'Useful context, without a scoreboard.', 'Sample progress describes skills, never rank. The stage selector records a prototype preference; activities stay fixed. Audio and reduced motion are separate controls. This preview has no child profiles or stored results.', 'Try the settings'],
 end: ['05 / ALL DONE', 'Let a good session end.', 'A calm goodbye gives the child permission to stop. No countdown, streak warning or next reward teaser. Returning home leaves their garden decoration in this open prototype session.', 'Back home'],
};

function wordmark(){return `<div class="wordmark">${pip()}<div>MathBuddy<small>A LITTLE WORLD OF NUMBERS</small></div></div>`;}
function header(activity = false) { return `<header class="child-header">${activity ? `<div class="activity-top"><button class="icon-button" data-action="home" aria-label="Go home">${icon('home')}</button></div><div class="round-progress" aria-label="Activity ${state.scene === 'count' ? '1' : state.scene === 'add' ? '2' : '3'} of 3"><b class="round-label">OUR LITTLE ADVENTURE</b>${['count','add','subtract'].map((s,i)=>`<span class="${s===state.scene?'current':i<['count','add','subtract'].indexOf(state.scene)?'done':''}"></span>`).join('')}</div><button class="quiet-button listen" data-action="listen" aria-label="Listen to this activity${state.narration?'':', narration is off'}">${icon('sound')} Listen</button>` : `${wordmark()}<button class="quiet-button" data-action="${state.scene==='parents'?'home':'parents-gate'}">${icon(state.scene==='parents'?'back':'lock')}${state.scene==='parents'?'Back to play':'Grown-ups'}</button>`}</header>`; }
function feedback(){return `<p class="feedback ${state.feedbackType}" id="feedback" role="status" aria-live="polite">${state.feedback || '&nbsp;'}</p>`;}
function title(kicker, heading, text){return `<div class="activity-title"><span class="eyebrow">${kicker}</span><h1>${heading}</h1><p>${text}</p></div>`;}
function renderHome(){return `${header()}<div class="home-content scene-enter"><section class="home-copy"><span class="eyebrow">A berry nice day</span><h1>Little numbers.<br><em>Big adventures.</em></h1><p>Let's make something<br>wonderful with Pip.</p><div class="home-actions"><button class="button primary" data-action="play">Play with Pip ${icon('arrow')}</button><button class="garden-link" data-action="garden">${icon('leaf')} My garden ${icon('arrow')}</button></div></section><div class="home-art">${homeArt()}<div class="speech-bubble">Hi, friend!</div></div></div><div class="home-bottom"><span class="tiny-flower">${icon('leaf')} A little play. A little discovery.</span><span class="edition">Count · wonder · grow</span></div>`;}
function renderCount(){return `${header(true)}${title('A picnic for Pip', 'Pack <span class="number">5</span> berries.', 'Tap a berry to put it in the basket.')}<div class="count-stage scene-enter"><div class="berry-patch" aria-label="Six berries to choose from">${Array.from({length:6},(_,i)=>`<button class="berry-button" data-berry="${i}" aria-label="Berry ${i+1}${state.picked.has(i)?', in the basket; tap to remove':', tap to put in the basket'}" aria-pressed="${state.picked.has(i)}" ${state.countDone?'disabled':''}>${berry()}<span class="pick-check" aria-hidden="true">✓</span></button>`).join('')}</div><div class="basket-area">${pip('pip-peek')}<div class="basket-fruit">${Array.from(state.picked,()=>berry()).join('')}</div>${basket()}<span class="basket-count" aria-label="${state.picked.size} berries in the basket">${state.picked.size}</span><span class="basket-caption">${state.countDone?'Just enough for our picnic.':'Tap a packed berry to take it out.'}</span></div></div><div class="activity-footer">${feedback()}<div class="action-row"><button class="button primary main-action" data-action="${state.countDone?'next-add':'check-count'}">${state.countDone?'Next':'Done'} ${icon(state.countDone?'arrow':'check')}</button>${!state.countDone?'<button class="reset-link" data-action="reset-count">Start over</button>':''}</div></div>`;}
function renderAdd(){return `${header(true)}${title('A friend brings one more', 'How many altogether?', state.joined?'Count the berries. Pick a number.':'Here are 2 berries. Here is 1 more.')}<div class="math-stage scene-enter"><div class="math-groups">${state.joined?`<div class="fruit-group joined-group" role="group" aria-label="Shared mat">${berry('',true).repeat(3)}</div>`:`<div class="fruit-group" role="group" aria-label="First mat">${berry('',true).repeat(2)}<span class="group-label">2</span></div><span class="math-symbol" aria-hidden="true">+</span><div class="fruit-group blue" role="group" aria-label="Second mat">${berry('',true)}<span class="group-label">1</span></div>`}</div>${state.joined?choices('add',[2,3,4],state.addDone):''}${state.addDone?'<div class="equation" aria-label="2 plus 1 equals 3">2 + 1 = 3</div>':''}</div><div class="activity-footer">${feedback()}${!state.joined?`<button class="button primary" data-action="join">Bring them together ${icon('arrow')}</button>`:state.addDone?`<button class="button primary" data-action="next-subtract">Next ${icon('arrow')}</button>`:''}</div>`;}
function choices(kind, values, done){return `<div class="choices" aria-label="Choose how many berries">${values.map(n=>`<button class="number-choice ${done&&n===3?'correct':''}" data-answer="${n}" data-kind="${kind}" ${done?'disabled':''} aria-label="${n} berries${done&&n===3?', correct':''}">${n}</button>`).join('')}</div>`;}
function renderSubtract(){return `${header(true)}${title('A little snack to share', state.given?'How many are left?':'Give Pip <span class="number">2</span> berries.', state.given?'Pip has 2. Count what is left.':'We have 5 berries. Pip would like 2.')}<div class="math-stage subtraction-stage scene-enter"><div class="math-groups"><div class="fruit-group" role="group" aria-label="Remaining mat">${Array.from({length:5},(_,i)=>berry(state.given&&i>=3?'given-fruit':'',!(state.given&&i>=3))).join('')}</div><div class="pip-receiver">${pip()}${state.given?`<div class="received-fruit" aria-label="Pip has two berries">${berry().repeat(2)}</div>`:''}</div></div>${state.given?choices('subtract',[2,3,4],state.subtractDone):''}${state.subtractDone?'<div class="equation" aria-label="5 take away 2 equals 3">5 − 2 = 3</div>':''}</div><div class="activity-footer">${feedback()}${!state.given?`<button class="button primary" data-action="give">Give Pip 2 ${icon('arrow')}</button>`:state.subtractDone?`<button class="button coral" data-action="reward">Visit my garden ${icon('leaf')}</button>`:''}</div>`;}
function renderGarden(){const hasReward=state.earned;return `${header()}<div class="garden-title scene-enter"><span class="eyebrow">YOUR LITTLE CORNER OF THE WORLD</span><h1>${hasReward&&!state.placed?'Look what<br>you grew!':'Hello,<br>little garden.'}</h1><p>${hasReward&&!state.placed?'You counted, added and shared. A new pinwheel is yours.':'A happy place to make your own.'}</p></div><div class="garden-canvas">${gardenArt()}</div>${hasReward&&!state.placed?`<section class="reward-panel scene-enter">${pinwheel()}<h2>A little bit of magic.</h2><p>${state.previewReward?'Sample reward for this preview.':'For your three little adventures.'}<br>Make it part of your garden.</p><button class="button primary" data-action="place">Plant my pinwheel ${icon('arrow')}</button></section>`:!state.placed?`<section class="reward-panel"><h2>This is your garden.</h2><p>Pip is happy you are here.<br>Play together to find a little decoration for this place.</p><button class="button primary" data-action="play">Play with Pip ${icon('arrow')}</button></section>`:''}${state.placed?`<button class="pinwheel-placed" data-action="spin" aria-label="Spin your pinwheel">${pinwheel()}<span>Tap to spin</span></button>`:''}<p class="garden-feedback" role="status" aria-live="polite">${state.feedback||''}</p><div class="garden-footer"><button class="reset-link" data-action="play">Play again</button><button class="button primary" data-action="finish">Done for today ${icon('check')}</button></div>`;}
function toggle(name,title,description){return `<div class="toggle-row"><div><strong id="${name}-label">${title}</strong><p>${description}</p></div><button class="toggle" role="switch" aria-checked="${state[name]}" aria-labelledby="${name}-label" data-setting="${name}"></button></div>`;}
function renderParents(){return `${header()}<div class="parent-content scene-enter"><div class="parent-title"><div><span class="eyebrow">THE GROWN-UP CORNER</span><h1>Small steps. Real discovery.</h1><p>Make room for curiosity, at your child's pace.</p></div><span class="sample-tag">ILLUSTRATIVE DATA ONLY</span></div><div class="parent-columns"><section><p class="section-caption">A starting point, not an age label</p><div class="level-setting"><h2>${state.level} with numbers</h2><p>${state.level==='Discovering'?'Explore matching, small sets and counting with a little help.':state.level==='Growing'?'Make and compare small sets. Explore adding and taking away.':'Explore place value, number bonds and different ways to solve.'}</p><div class="level-options" aria-label="Choose a sample learning stage">${['Discovering','Growing','Exploring'].map(l=>`<button class="level-option" data-level="${l}" aria-pressed="${state.level===l}">${l}</button>`).join('')}</div></div><p class="level-note">Preference changes this preview only. The three sample activities stay the same; no adaptive engine is implemented.</p><div style="margin-top:23px"><p class="section-caption">Make it comfortable</p>${toggle('narration','Narration','Opt-in synthetic voice · tap Listen in an activity')}${toggle('music','Music','Quiet synthesized preview · off by default')}${toggle('reducedMotion','Reduced motion','Keep the story still and the feedback clear')}</div><p class="parent-status" role="status" aria-live="polite">${state.feedback||''}</p></section><section><p class="section-caption">How a progress summary could look</p><div class="skill-list"><div class="skill-row"><strong>Counting small sets</strong><span>4 of 6 tries without extra help</span><p class="sample-evidence">2 tries with extra help</p></div><div class="skill-row"><strong>Adding within 5</strong><span>2 of 5 tries without extra help</span><p class="sample-evidence">3 tries with extra help</p></div><div class="skill-row"><strong>Taking away</strong><span>1 of 4 tries without extra help</span><p class="sample-evidence">3 tries with extra help</p></div></div><div class="section-caption">Try it away from the screen</div><h2 style="font-family:var(--round);font-size:24px;line-height:1.25;letter-spacing:-.7px;margin:0 0 12px">“Can you find five<br>things for our picnic?”</h2><p class="parent-footnote">Gather spoons, blocks or toy animals. Let your child move each one as they count. Wonder together: “What happens if we add one more?”</p><p class="parent-footnote">All progress shown here is a design example, not a record of your child. Settings and garden changes last only while this page is open. No accounts, analytics or child data are collected.</p></section></div></div>`;}
function renderEnd(){return `${header()}<section class="end-content scene-enter">${pip()}<h1>That was lovely.</h1><p>Your garden will be here.<br>Time for a little real-world adventure.</p><button class="button primary" data-action="home">Back home ${icon('home')}</button></section>`;}

function render({focus=false}={}) {
  const sceneFns={home:renderHome,count:renderCount,add:renderAdd,subtract:renderSubtract,garden:renderGarden,parents:renderParents,end:renderEnd};
  app.innerHTML=sceneFns[state.scene]();
  document.body.classList.toggle('reduce-motion',state.reducedMotion);
  const note=notes[state.scene];
  ['note-number','note-title','note-text','interaction-hint'].forEach((id,i)=>document.getElementById(id).textContent=note[i]);
  document.querySelectorAll('[data-preview]').forEach(button=>{if(button.dataset.preview===state.scene)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');});
  if(focus){const heading=app.querySelector('h1');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}}
}
function navigate(scene,preview=false){stopSpeech();state.scene=scene;state.feedback='';state.feedbackType='';if(preview&&scene==='garden'&&!state.earned){state.earned=true;state.previewReward=true;}render({focus:true});}
function startPlay(){state.picked=new Set();state.countDone=false;state.joined=false;state.addDone=false;state.given=false;state.subtractDone=false;state.previewReward=false;navigate('count');}
function announce(message,type=''){state.feedback=message;state.feedbackType=type;const el=app.querySelector('#feedback,.garden-feedback,.parent-status');if(el){el.textContent=message;el.classList.toggle('hint',type==='hint');el.classList.toggle('success',type==='success');}}

let audioContext; let musicTimer; const musicNodes=new Set();
function musicNote(frequency,when,duration=.65){const oscillator=audioContext.createOscillator();const gain=audioContext.createGain();oscillator.type='sine';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(0,when);gain.gain.linearRampToValueAtTime(.026,when+.06);gain.gain.exponentialRampToValueAtTime(.0001,when+duration);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start(when);oscillator.stop(when+duration+.03);musicNodes.add(oscillator);oscillator.onended=()=>musicNodes.delete(oscillator);}
function stopMusic(){clearInterval(musicTimer);musicTimer=undefined;musicNodes.forEach(node=>{try{node.stop();}catch{}});musicNodes.clear();}
async function updateMusic(){stopMusic();if(!state.music)return;try{const AudioContextClass=window.AudioContext||window.webkitAudioContext;if(!AudioContextClass)throw new Error('unavailable');audioContext ||= new AudioContextClass();await audioContext.resume();if(!state.music)return;const phrase=()=>{if(!state.music||document.hidden)return;[261.63,329.63,392,329.63,293.66,261.63].forEach((f,i)=>musicNote(f,audioContext.currentTime+.05+i*.7));};phrase();musicTimer=setInterval(phrase,6500);}catch{state.music=false;render();announce('Audio preview is unavailable in this browser.');}}
function stopSpeech(){if('speechSynthesis' in window)window.speechSynthesis.cancel();}
function listen(){if(!state.narration){announce('Narration is off. A grown-up can turn it on.','hint');return;}if(!('speechSynthesis' in window)){announce('The voice preview is unavailable in this browser.','hint');return;}stopSpeech();const words=state.scene==='count'?'Help Pip pack five berries. Tap a berry to put it in the basket.':state.scene==='add'?(state.joined?'How many berries are there altogether?':'Here are two berries. Here is one more. Bring them together.'):(state.given?'Pip has two berries. How many are left?':'We have five berries. Give Pip two.');const utterance=new SpeechSynthesisUtterance(words);utterance.rate=.83;utterance.pitch=1.12;window.speechSynthesis.speak(utterance);}

document.querySelector('.review-nav').addEventListener('click',event=>{if(event.target.closest('[data-reset-demo]')){stopMusic();stopSpeech();Object.assign(state,{scene:'home',picked:new Set(),countDone:false,joined:false,addDone:false,given:false,subtractDone:false,earned:false,placed:false,finished:false,narration:false,music:false,reducedMotion:window.matchMedia('(prefers-reduced-motion: reduce)').matches,level:'Growing',feedback:'',feedbackType:'',previewReward:false});render({focus:true});return;}const button=event.target.closest('[data-preview]');if(button)navigate(button.dataset.preview,true);});
app.addEventListener('click',event=>{
 const button=event.target.closest('button');if(!button||button.disabled)return;
 if(button.dataset.berry!==undefined){const i=Number(button.dataset.berry);state.picked.has(i)?state.picked.delete(i):state.picked.add(i);state.feedback='';state.feedbackType='';render();app.querySelector(`[data-berry="${i}"]`)?.focus({preventScroll:true});return;}
 if(button.dataset.answer){const correct=button.dataset.answer==='3';if(correct){state[button.dataset.kind==='add'?'addDone':'subtractDone']=true;state.feedback=button.dataset.kind==='add'?'Yes! 2 and 1 make 3.':'Yes! 3 berries are left.';state.feedbackType='success';render();}else{button.classList.add('incorrect');announce(button.dataset.kind==='add'?'Let’s count them together. One, two, three.':'Look at the berries left on the mat. One, two, three.','hint');}return;}
 if(button.dataset.level){state.level=button.dataset.level;state.feedback=`${state.level} selected. Sample activities stay the same.`;render();app.querySelector(`[data-level="${state.level}"]`)?.focus({preventScroll:true});return;}
 if(button.dataset.setting){const key=button.dataset.setting;state[key]=!state[key];if(key==='narration'&&!state.narration)stopSpeech();state.feedback=`${key==='reducedMotion'?'Reduced motion':key==='music'?'Music':'Narration'} ${state[key]?'on':'off'}.`;render();app.querySelector(`[data-setting="${key}"]`)?.focus({preventScroll:true});if(key==='music')updateMusic();return;}
 switch(button.dataset.action){
  case 'home':navigate('home');break;
  case 'play':startPlay();break;
  case 'garden':navigate('garden');break;
  case 'parents-gate':document.getElementById('parent-gate').showModal();break;
  case 'listen':listen();break;
  case 'reset-count':state.picked.clear();state.feedback='Try packing 5 berries.';render();break;
  case 'check-count':if(state.picked.size===5){state.countDone=true;state.feedback='Five berries! A perfect little picnic.';state.feedbackType='success';render();}else announce(state.picked.size<5?`You have ${state.picked.size}. Let’s find ${5-state.picked.size} more.`:'You packed 6. Tap one packed berry to take it out.','hint');break;
  case 'next-add':navigate('add');break;
  case 'join':state.joined=true;state.feedback='';render();break;
  case 'next-subtract':navigate('subtract');break;
  case 'give':state.given=true;state.feedback='';render();break;
  case 'reward':state.earned=true;state.previewReward=false;state.placed=false;navigate('garden');break;
  case 'place':state.placed=true;state.feedback='Your pinwheel looks happy here. Tap it to spin!';render();break;
  case 'spin':button.classList.remove('spinning');void button.offsetWidth;button.classList.add('spinning');announce(state.reducedMotion||window.matchMedia('(prefers-reduced-motion: reduce)').matches?'A lovely pinwheel! Motion is kept still.':'Round and round. What a lovely garden!');break;
  case 'finish':stopMusic();state.music=false;state.finished=true;navigate('end');break;
 }
});
document.getElementById('gate-cancel').addEventListener('click',()=>document.getElementById('parent-gate').close());
document.getElementById('gate-continue').addEventListener('click',()=>{document.getElementById('parent-gate').close();navigate('parents');});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopSpeech();stopMusic();}else if(state.music)updateMusic();});
window.addEventListener('pagehide',()=>{stopMusic();stopSpeech();});
render();
